const MenuItems = [
  {
    id: 11,
    category: "Entrada",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/ensala10.png",
    title: "1. Ensalada",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 11,00",
    btnAdd: "+ ADD",
  },
  {
    id: 12,
    category: "Entrada",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Ensalada",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 13,
    category: "Entrada",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Ensalada",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 23,00",
    btnAdd: "+ ADD",
  },
  {
    id: 21,
    category: "Pollo",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Pollo",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 22,
    category: "Pollo",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Pollo",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 23,
    category: "Pollo",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Pollo",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 31,
    category: "Burguer",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Burguer",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 32,
    category: "Burguer",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Burguer",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 33,
    category: "Burguer",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Burguer",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
];
export { MenuItems };
