const MenuItems = [
  {
    id: 11,
    category: "Entrada",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/ensala10.png",
    title: "1. Ensalada",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 11,00",
    btnAdd: "+ ADD",
  },
  {
    id: 12,
    category: "Entrada",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Ensalada",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 13,
    category: "Entrada",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Ensalada",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 23,00",
    btnAdd: "+ ADD",
  },
  {
    id: 21,
    category: "Pollo",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Pollo",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 22,
    category: "Pollo",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Pollo",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 23,
    category: "Pollo",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Pollo",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 31,
    category: "Burger",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Burger",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 32,
    category: "Burger",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Burger",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 33,
    category: "Burger",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Burger",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 41,
    category: "Postres",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Postres",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 42,
    category: "Postres",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Postres",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 43,
    category: "Postres",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Postres",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },

  {
    id: 51,
    category: "Bebidas Frias",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Bebidas Frias",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 52,
    category: "Bebidas Frias",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Bebidas Frias",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 53,
    category: "Bebidas Frias",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Bebidas Frias",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 61,
    category: "Aperitivos",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Aperitivos",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 62,
    category: "Aperitivos",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Aperitivos",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 63,
    category: "Aperitivos",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Aperitivos",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 71,
    category: "Bebidas Calientes",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Bebidas Calientes",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 72,
    category: "Bebidas Calientes",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "2. Bebidas Calientes",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 73,
    category: "Bebidas Calientes",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "3. Bebidas Calientes",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },

  {
    id: 81,
    category: "El Restaurante",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. El Restaurante",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 91,
    category: "Noticias",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Noticias",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
  {
    id: 101,
    category: "Patrocinadores",
    image: "https://i94.servimg.com/u/f94/20/44/55/20/plato10.png",
    title: "1. Patrocinadores",
    description: "Medium | Cheese, hungarian pepper",
    price: "Bs. 22,00",
    btnAdd: "+ ADD",
  },
];
export { MenuItems };
